# permissions for end users to view clusterissuers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterissuer-viewer-role
rules:
- apiGroups:
  - certmanager.freeipa.org
  resources:
  - clusterissuers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certmanager.freeipa.org
  resources:
  - clusterissuers/status
  verbs:
  - get
